image: "python:3.7"

before_script:
    - python --version
    - pip install -r requirements.txt

stages:
  - Test

tests:
    stage: Test
    script: 
        - coverage run -m unittest discover --verbose
        - coverage report -m 
