[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pybind11>=2.6.0",
    "ioh>=0.3.14",
    "numpy>=1.18.5, <2.0.0",
    "mypy",
    "pybind11>=2.6.0",
    "scipy>=1.5.1",
]

build-backend = "setuptools.build_meta"