class Placement:
    def __init__(self, *args, **kwargs) -> None: ...
    def __call__(self, parameters) -> None: ...

class Uniform(Placement):
    def __init__(self) -> None: ...

class X0(Placement):
    def __init__(self) -> None: ...

class Zero(Placement):
    def __init__(self) -> None: ...
