from typing import Callable

import numpy

class Gaussian(Sampler):
    def __init__(self, d: int) -> None: ...
    def __call__(self) -> numpy.ndarray: ...

class Halton(Sampler):
    def __init__(self, d: int, i: int = ...) -> None: ...
    def __call__(self) -> numpy.ndarray: ...

class Mirrored(Sampler):
    def __init__(self, sampler: Sampler) -> None: ...
    def __call__(self) -> numpy.ndarray: ...

class Orthogonal(Sampler):
    def __init__(self, sampler: Sampler, n_samples: int) -> None: ...
    def __call__(self) -> numpy.ndarray: ...

class PySampler(Sampler):
    def __init__(self, d: int, function: Callable[[], float]) -> None: ...
    def __call__(self) -> numpy.ndarray: ...

class Sampler:
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def d(self) -> int: ...

class Sobol(Sampler):
    def __init__(self, d: int) -> None: ...
    def __call__(self) -> numpy.ndarray: ...

class Uniform(Sampler):
    def __init__(self, d: int) -> None: ...
    def __call__(self) -> numpy.ndarray: ...
