import modcma.c_maes.cmaescpp
import modcma.c_maes.cmaescpp.parameters

class Elitsm:
    def __init__(self) -> None: ...
    def __call__(self, parameters: modcma.c_maes.cmaescpp.Parameters) -> None: ...

class NoElitsm(Elitsm):
    def __init__(self) -> None: ...
    def __call__(self, parameters: modcma.c_maes.cmaescpp.Parameters) -> None: ...

class NoPairwise(Pairwise):
    def __init__(self) -> None: ...
    def __call__(self, parameters: modcma.c_maes.cmaescpp.Parameters) -> None: ...

class Pairwise:
    def __init__(self) -> None: ...
    def __call__(self, parameters: modcma.c_maes.cmaescpp.Parameters) -> None: ...

class Strategy:
    elitsm: Elitsm
    pairwise: Pairwise
    def __init__(self, modules: modcma.c_maes.cmaescpp.parameters.Modules) -> None: ...
    def select(self, parameters: modcma.c_maes.cmaescpp.Parameters) -> None: ...
