from typing import List, Tuple

def compute_ert(running_times: List[int], budget: int) -> Tuple[float, int]: ...
def random_normal() -> float: ...
def random_uniform() -> float: ...
def set_seed(seed: int) -> None: ...
